### ISSUE TITLE
Boulder County precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-co#11]
Can be found [here](http://www.bouldercounty.org/elections/results/pages/default.aspx), and seem to be Excel or HTML back to 2008.
- [x] 2012 general
- [ ] 2012 primary
- [ ] 2010 primary
- [ ] 2008 primary

**Comment by miroli** [comment]
I can take this one.

**Comment by miroli** [comment]
@dwillis Should the result include non-office votes (ballots, amendments etc)?

**Comment by dwillis** [comment]
No, you can exclude those.

**Comment by miroli** [comment]
Ok. I've submitted a pull request. Hope everything looks ok. I've also uploaded a [Jupyter notebook](https://github.com/miroli/open_elections_demo/blob/master/Boulder.ipynb) if you want to take a look at my process. If that looks good as well, I'll continue with the rest of the Boulder results.

**Comment by dwillis** [comment]
Looks great, and thanks for the notebook example, too. Can we use that as a reference in our docs?

**Comment by miroli** [comment]
Sure!
