### ISSUE TITLE
Larimer County precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-co#19]
Electronic PDF files are [available](https://www.larimer.org/clerk/elections/records-data/past-info/results) back to 2000.
- [ ] 2012 general
- [ ] 2012 primary
- [ ] 2010 primary
- [ ] 2008 primary
- [ ] 2006 primary
- [ ] 2004 primary
- [ ] 2002 general
- [ ] 2000 general
- [ ] 2002 primary
- [ ] 2000 primary

**Comment by chipoglesby** [comment]
I'd like to work on the results for Larmier county!

**Comment by dwillis** [comment]
Awesome, thanks @chipoglesby! We recommend using Tabula to convert electronic PDFs, and the result should look something like https://github.com/openelections/openelections-data-co/blob/master/2014/20141104__co__general__dolores__precinct.csv (don't need total_ballots if it's not there).

**Comment by chipoglesby** [comment]
@dwillis sorry, I haven't forgotten about this yet. I hope to be able to set down and start working on this soon!
