### ISSUE TITLE
Pitkin County precinct results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-co#22]
2006-2014 are in electronic PDFs or Google spreadsheets [here](http://www.pitkinvotes.org/home/historical-election-data). We need:
- [x] [2012 general](https://docs.google.com/file/d/0B0fdDWQSJaPfTlU4Q1I3b2FZRUU/edit)
- [ ] [2012 primary](https://drive.google.com/file/d/0B0fdDWQSJaPfOHNOVzV2bGhSVG8/view)

**Comment by nalkash36952** [comment]
I'll take this one.
