### ISSUE TITLE
HTML scraper for 2012 primary results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-co#6]
For each party listed [here](http://www.sos.state.co.us/pubs/elections/Results/Abstract/2012/primary/index.html), convert results into a single CSV file called `20120626__co__primary.csv` with the following headers:

`county`, `office`, `district`, `party`, `candidate`,`votes`

You only need to have the following offices: U.S. House, State Senate, State Representative, but if you want to include others that's fine. For total results, leave the `candidate` blank.

**Comment by austinclemens** [comment]
I am working on this (hopefully it will be 1 scraper that can handle both these issues)
