### ISSUE TITLE
HTML scraper for 2014 general results

### ISSUE THREAD

**Issue by dwillis** [openelections/openelections-data-co#7]
For each party listed [here](http://www.sos.state.co.us/pubs/elections/Results/Abstract/2014/general/index.html), convert results into a single CSV file called `20141104__co__general.csv` with the following headers:

`county`, `office`, `district`, `party`, `candidate`,`votes`

You only need to have the following offices: Governor, state offices, U.S. House, State Senate, State Representative, but if you want to include others that's fine. For total results, leave the `candidate` blank.

**Comment by austinclemens** [comment]
I am working on this
